// Generated by CoffeeScript 1.6.3
var path;

path = require('path');

exports.help = function() {
  var version;
  version = require(path.join(__dirname, '..', 'package.json')).version;
  return console.log("GHFM " + ('v' + version).grey + "\n" + 'Github Flavored Markdown previwer'.grey + "\n\nUsage:\n  ghfm [" + 'path'.green + "]\n\nExamples:\n    ghfm " + '/path/to/my/file.md'.green);
};

/*
//@ sourceMappingURL=cli.map
*/
