// Generated by CoffeeScript 1.6.3
var connect, exec, io, open, opened, path, refresher, root;

path = require('path');

exec = require('child_process').exec;

io = require('socket.io');

connect = require('connect');

refresher = null;

root = path.join(__dirname, '..', 'public');

module.exports = function() {
  var address, app, port;
  port = 54321;
  app = connect().use(connect["static"](root)).use(connect["static"](path.join(__dirname, '..'))).listen(port);
  address = 'http://localhost:' + port;
  console.log("♫  Preview running at " + address);
  refresher = io.listen(12345, {
    'log level': 0
  });
  open();
  return module.exports;
};

module.exports.push = function(html) {
  return refresher.sockets.emit('refresh', html);
};

opened = false;

open = function() {
  if (opened) {
    return;
  }
  opened = true;
  return exec('open http://localhost:54321 > /dev/null');
};

/*
//@ sourceMappingURL=server.map
*/
